-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'WAITING_DEPOSIT';

-- AlterTable
ALTER TABLE "Payment"
  ADD COLUMN IF NOT EXISTS "vbankBank"     VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "vbankCode"     VARCHAR(10),
  ADD COLUMN IF NOT EXISTS "vbankNumber"   VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "vbankHolder"   VARCHAR(60),
  ADD COLUMN IF NOT EXISTS "vbankDueDate"  TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "vbankSecret"   VARCHAR(64);
